# Generated by Django 5.0.6 on 2024-05-15 22:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "ordering": ["-date", "user"],
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
            },
        ),
        migrations.AlterModelOptions(
            name="weightentry",
            options={"ordering": ["-date", "user"], "verbose_name": "WeigtEnty"},
        ),
    ]
