# Generated by Django 5.0.6 on 2024-05-19 02:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker_app", "0002_alter_activity_options_alter_weightentry_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weightentry",
            options={"ordering": ["-date", "user"], "verbose_name": "WeigtEntry"},
        ),
    ]
